import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Jiazi',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: '7 up',
      category: 'beverage',
      image: '/images/p1.jpg',
      price: 2.49,
      countInStock: 100,
      brand: '7 up',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Polar',
      category: 'beverage',
      image: '/images/p2.jpg',
      price: 3.00,
      countInStock: 20,
      brand: 'Polar',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Izze Sparkling Water',
      category: 'beverage',
      image: '/images/p3.jpg',
      price: 1.49,
      countInStock: 0,
      brand: 'Izze',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Top Ramen',
      category: 'fastfood',
      image: '/images/p4.jpg',
      price: 0.59,
      countInStock: 100,
      brand: 'Top Ramen',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Marcon and Chesse',
      category: 'fastfood',
      image: '/images/p5.jpg',
      price: 3.49,
      countInStock: 20,
      brand: 'Kruft',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: "Annie's Homegrown Macaroni & Cheese, White Cheddar",
      category: 'fastfood',
      image: '/images/p6.jpg',
      price: 2.09,
      countInStock: 12,
      brand: 'Annie',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
